# Amber Material High Contrast — PowerShell 7 / PSReadLine
# Generated by scripts/build_terminal_suite.py; edit the source palettes instead.
#Requires -Version 7.2

$AmberMaterialEscape = [char]0x1b
$AmberMaterialColors = @{
    ContinuationPrompt      = "#888B84"
    Emphasis                = "#FFE08A"
    Error                   = "#FF6B6B"
    Selection               = "${AmberMaterialEscape}[38;2;255;244;214;48;2;74;63;40m"
    Default                 = "#E7E1D1"
    Comment                 = "#888B84"
    Keyword                 = "#D9A0FF"
    String                  = "#B8D96D"
    Operator                = "#66D9D0"
    Variable                = "#D9A0FF"
    Command                 = "#FFCB6B"
    Parameter               = "#FFE08A"
    Type                    = "#70B7FF"
    Number                  = "#D0EA8A"
    Member                  = "#94CAFF"
    InlinePrediction        = "#888B84"
    ListPrediction          = "#E7E1D1"
    ListPredictionSelected  = "${AmberMaterialEscape}[38;2;29;32;33;48;2;255;203;107m"
    ListPredictionTooltip   = "#888B84"
}

if (Get-Module -ListAvailable -Name PSReadLine) {
    Import-Module PSReadLine
    Set-PSReadLineOption -Colors $AmberMaterialColors
}
