#!/usr/bin/env python3
"""Generate the warm, high-contrast Amber Material themes for Ghostty.

The terminal palette is intentionally independent from the VS Code token
palette. It combines a Gruvbox Material-style warm background with the clear
ANSI separation of Material Design Colors while retaining amber as the theme's
identity accent.
"""
import os

from variants import ROOT, VARIANTS


def build(variant):
    dst = ROOT / variant.ghostty_path
    lines = [
        f"# {variant.name} — Ghostty theme",
        "# Generated by scripts/build_ghostty.py; edit the palette there, not here.",
        "# Warm Gruvbox Material-inspired base with high-contrast Material ANSI colors.",
        "",
        f"background = {variant.ghostty_background}",
        f"foreground = {variant.ghostty_foreground}",
        "",
        f"cursor-color = {variant.ghostty_cursor}",
        f"cursor-text = {variant.ghostty_background}",
        "",
        f"selection-background = {variant.ghostty_selection_bg}",
        f"selection-foreground = {variant.ghostty_selection_fg}",
        "",
    ]
    for idx, color in enumerate(variant.ghostty_ansi):
        lines.append(f"palette = {idx}={color}")

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {dst}: {len(variant.ghostty_ansi)} palette entries")


def main():
    for variant in VARIANTS:
        build(variant)


if __name__ == "__main__":
    main()
