#!/usr/bin/env python3
"""Generate the Grok Build palette export and pager.toml from the source palettes.

Two outputs per variant, because Grok splits appearance across two mechanisms and
only one of them is open to us today.
"""
import json

import ghostty_palette
from variants import ROOT, VARIANTS


def flatten(color, over):
  """Composite a #RRGGBBAA VS Code color onto an opaque backdrop."""
  if not (isinstance(color, str) and color.startswith("#") and len(color) == 9):
    return color
  alpha = int(color[7:9], 16) / 255
  channels = (
    round(int(color[i:i + 2], 16) * alpha + int(over[i:i + 2], 16) * (1 - alpha))
    for i in (1, 3, 5)
  )
  return "#" + "".join(f"{channel:02X}" for channel in channels)


def build(variant):
  vscode_src = ROOT / variant.vscode_path
  ghostty_src = ROOT / variant.ghostty_path
  json_dst = ROOT / variant.grok_json_path
  pager_dst = ROOT / variant.grok_pager_path

  with open(vscode_src, encoding="utf-8") as source:
    vscode_theme = json.load(source)

  options, ansi = ghostty_palette.load(ghostty_src)
  ui = vscode_theme["colors"]

  background = options["background"]
  foreground = options["foreground"]
  amber = options["cursor-color"]
  selection = options["selection-background"]

  surface = ui["editor.background"]
  surface_deep = ui["activityBar.background"]
  surface_raised = ui["editorWidget.background"]
  border = ui["editorWidget.border"]
  dim = ansi[8]
  muted = ui["descriptionForeground"]
  surface_highlight = ui["editorIndentGuide.background1"]

  theme = {
    "name": variant.name,
    "backgrounds": {
      "bg_base": background,
      "bg_light": surface_raised,
      "bg_dark": surface_deep,
      "bg_highlight": surface_highlight,
      "bg_hover": flatten(ui["menu.selectionBackground"], surface),
      "bg_terminal": background,
      "bg_visual": selection,
    },
    "accents": {
      "accent_user": amber,
      "accent_assistant": ansi[4],
      "accent_thinking": ansi[5],
      "accent_tool": ansi[6],
      "accent_system": dim,
      "accent_error": ansi[1],
      "accent_success": ansi[2],
      "accent_running": ansi[11],
      "accent_skill": ansi[13],
      "accent_plan": ansi[12],
      "accent_verify": ansi[10],
      "accent_feedback": ansi[14],
      "accent_remember": ansi[5],
      "accent_model": ansi[9],
    },
    "text": {
      "text_primary": foreground,
      "text_secondary": muted,
    },
    "grays": {
      "gray_dim": border,
      "gray": dim,
      "gray_bright": ansi[15],
    },
    "semantic": {
      "command": amber,
      "path": ansi[6],
      "running": ansi[11],
      "warning": ansi[3],
      "fuzzy_accent": ansi[11],
    },
    "borders": {
      "selection_border": amber,
      "hover_border": border,
      "prompt_border": border,
      "prompt_border_active": amber,
      "scrollbar_bg": surface_deep,
      "scrollbar_fg": border,
    },
    "paste": {
      "paste_bg": surface_raised,
      "paste_fg": foreground,
      "paste_dim": dim,
    },
    "diff": {
      "diff_delete_bg": flatten(ui["diffEditor.removedLineBackground"], surface),
      "diff_delete_fg": ansi[9],
      "diff_insert_bg": flatten(ui["diffEditor.insertedLineBackground"], surface),
      "diff_insert_fg": ansi[10],
      "diff_equal_fg": foreground,
      "diff_gutter_fg": dim,
    },
    "markdown": {
      "md_heading_h1": amber,
      "md_heading_h2": ansi[11],
      "md_heading_h3": ansi[4],
      "md_heading_h4": ansi[12],
      "md_heading_h5": ansi[5],
      "md_heading_h6": ansi[13],
      "md_code": ansi[2],
      "md_code_bg": surface,
      "md_text": foreground,
      "md_muted": dim,
      "md_task_checked": ansi[2],
      "md_task_unchecked": dim,
      "link_fg": ansi[4],
    },
  }

  json_dst.parent.mkdir(parents=True, exist_ok=True)
  with open(json_dst, "w", encoding="utf-8") as destination:
    json.dump(theme, destination, indent=2, ensure_ascii=False)
    destination.write("\n")

  slot_count = sum(
    len(value) for value in theme.values() if isinstance(value, dict)
  )

  prompt_bg = "light"
  pager = f"""# {variant.name} — Grok Build pager
# Generated by scripts/build_grok_theme.py; edit the source palettes instead.
# Install to ~/.grok/pager.toml (see README).
#
# Grok's `[ui].theme` only accepts its five built-in themes, so the surrounding
# TUI keeps whichever of those is active. These are the appearance settings Grok
# does read from disk.

[scrollback.layout]
outer_vpad = 1
outer_hpad_left = 2
outer_hpad_right = 2
block_pad_left = 2
block_pad_right = 2

[scrollback.scrollbar]
enabled = true
gap_left = 0
gap_right = 0
scrollbar_bg = "{surface_deep}"
scrollbar_fg = "{border}"

[scrollback.display]
sticky_headers = true
expandable_indicator = true
# Amber Material runs high-contrast, so dimmed accents stay further from the
# background than Grok's 0.5 default to keep collapsed blocks legible.
dim_accent = 0.6

[animation]
fps = 30
wave_rows = 32

[scrollback.blocks.edit]
indent = true
hunk_separator = "…"
dual_line_numbers = false
bg = "{variant.grok_pager_block_bg}"

[scrollback.blocks.thinking]
accent_enabled = true
animate = true
truncated_lines = 3
bg_blend = 70
header = true
header_bright = false

[scrollback.blocks.tool]
muted_collapsed = true
dim_details = true
bullet = "diamond"

[scrollback.blocks.execute]
accent_enabled = true
header_style = "label"
muted_command_collapsed = true
first_lines = 2
last_lines = 3

[scrollback.blocks.prompt]
vpad = true
bg = "{prompt_bg}"
show_prefix = true
min_lines = 2

[prompt]
collapse_unfocused = true
mouse_hover = true
show_prefix = true
"""

  with open(pager_dst, "w", encoding="utf-8") as destination:
    destination.write(pager)

  print(f"wrote {json_dst}: {slot_count} color slots")
  print(f"wrote {pager_dst}")


def main():
  for variant in VARIANTS:
    build(variant)


if __name__ == "__main__":
  main()
