#!/usr/bin/env python3
"""Generate the warm, high-contrast Amber Material theme for Ghostty.

The terminal palette is intentionally independent from the VS Code token
palette. It combines a Gruvbox Material-style warm background with the clear
ANSI separation of Material Design Colors while retaining amber as the theme's
identity accent.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

DST = os.path.join(ROOT, "ghostty", "amber-material")

# Warm near-black surfaces and bright, slightly warm text.
BACKGROUND = "#1D2021"
FOREGROUND = "#E7E1D1"
AMBER = "#FFCB6B"
SELECTION_BACKGROUND = "#4A3F28"
SELECTION_FOREGROUND = "#FFF4D6"

# ANSI colors: normal 0-7, bright 8-15.
ANSI = [
    "#1D2021",  # black
    "#FF6B6B",  # red
    "#B8D96D",  # green
    AMBER,      # yellow
    "#70B7FF",  # blue
    "#D9A0FF",  # magenta
    "#66D9D0",  # cyan
    FOREGROUND, # white
    "#888B84",  # bright black
    "#FF8787",  # bright red
    "#D0EA8A",  # bright green
    "#FFE08A",  # bright yellow
    "#94CAFF",  # bright blue
    "#E8BDFF",  # bright magenta
    "#8BE9E1",  # bright cyan
    "#FFFFFF",  # bright white
]

lines = [
    "# Amber Material High Contrast — Ghostty theme",
    "# Generated by scripts/build_ghostty.py; edit the palette there, not here.",
    "# Warm Gruvbox Material-inspired base with high-contrast Material ANSI colors.",
    "",
    f"background = {BACKGROUND}",
    f"foreground = {FOREGROUND}",
    "",
    f"cursor-color = {AMBER}",
    f"cursor-text = {BACKGROUND}",
    "",
    f"selection-background = {SELECTION_BACKGROUND}",
    f"selection-foreground = {SELECTION_FOREGROUND}",
    "",
]

for idx, color in enumerate(ANSI):
    lines.append(f"palette = {idx}={color}")

os.makedirs(os.path.dirname(DST), exist_ok=True)
with open(DST, "w") as fh:
    fh.write("\n".join(lines) + "\n")

print(f"wrote {DST}: {len(ANSI)} palette entries")
