#!/usr/bin/env python3
"""Generate a Ghostty theme from the same palette as the VS Code theme.

Ghostty reads a flat key = value config. The ANSI palette is taken from the
built VS Code theme's terminal.* slots so the two stay in sync: edit the VS Code
build script, rerun both, and the terminal follows.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

SRC = os.path.join(ROOT, "themes", "palenight-amber-hc.json")
DST = os.path.join(ROOT, "ghostty", "palenight-amber")

colors = json.load(open(SRC))["colors"]

# Ghostty palette index -> VS Code terminal slot.
ANSI = [
    ("terminal.ansiBlack",         0), ("terminal.ansiRed",           1),
    ("terminal.ansiGreen",         2), ("terminal.ansiYellow",        3),
    ("terminal.ansiBlue",          4), ("terminal.ansiMagenta",       5),
    ("terminal.ansiCyan",          6), ("terminal.ansiWhite",         7),
    ("terminal.ansiBrightBlack",   8), ("terminal.ansiBrightRed",     9),
    ("terminal.ansiBrightGreen",  10), ("terminal.ansiBrightYellow", 11),
    ("terminal.ansiBrightBlue",   12), ("terminal.ansiBrightMagenta",13),
    ("terminal.ansiBrightCyan",   14), ("terminal.ansiBrightWhite",  15),
]


def hex6(value):
    """Ghostty wants #RRGGBB — drop any alpha channel."""
    return value[:7]


lines = [
    "# Palenight Amber — Ghostty theme",
    "# Generated by scripts/build_ghostty.py; edit the palette there, not here.",
    "",
    f"background = {hex6(colors['terminal.background'])}",
    f"foreground = {hex6(colors['terminal.foreground'])}",
    "",
    f"cursor-color = {hex6(colors['terminalCursor.foreground'])}",
    f"cursor-text = {hex6(colors['terminalCursor.background'])}",
    "",
    f"selection-background = {hex6(colors['terminal.selectionBackground'])}",
    f"selection-foreground = {hex6(colors['terminal.foreground'])}",
    "",
]

for slot, idx in ANSI:
    lines.append(f"palette = {idx}={hex6(colors[slot])}")

os.makedirs(os.path.dirname(DST), exist_ok=True)
with open(DST, "w") as fh:
    fh.write("\n".join(lines) + "\n")

print(f"wrote {DST}: {len(ANSI)} palette entries")
