#!/usr/bin/env python3
"""Read the Ghostty theme, the source of truth for the terminal palette.

`ghostty/amber-material` is generated by build_ghostty.py and consumed by every
other builder: the VS Code theme takes its 16 ANSI colors from here, and the
Codex and terminal-suite builders take their surfaces too. Keeping one parser
means a malformed palette fails the same way everywhere instead of silently
producing a theme with holes in it.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

SOURCE = os.path.join(ROOT, "ghostty", "amber-material")

# Every consumer needs the full 16-color palette plus these surfaces, so the
# loader validates the superset rather than making each caller restate it.
REQUIRED_OPTIONS = (
    "background",
    "foreground",
    "cursor-color",
    "selection-background",
    "selection-foreground",
)

# Index into the ANSI list returned by load(). Callers read e.g. ANSI_NAMES[1]
# for red; the VS Code builder uses these to name its terminal.ansi* keys.
ANSI_NAMES = (
    "Black", "Red", "Green", "Yellow", "Blue", "Magenta", "Cyan", "White",
    "BrightBlack", "BrightRed", "BrightGreen", "BrightYellow",
    "BrightBlue", "BrightMagenta", "BrightCyan", "BrightWhite",
)


def load(path=SOURCE):
    """Return (options, ansi) parsed from a Ghostty theme file.

    `options` maps Ghostty color option names to hex strings; `ansi` maps the
    16 palette indices to hex strings. A repeated key takes its last value,
    matching how Ghostty itself resolves a config. Raises ValueError if any
    required option or palette index is missing.
    """
    options = {}
    ansi = {}
    with open(path, encoding="utf-8") as source:
        for raw_line in source:
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = (part.strip() for part in line.split("=", 1))
            if key == "palette":
                index, color = value.split("=", 1)
                ansi[int(index)] = color.strip()
            else:
                options[key] = value

    missing_options = sorted(set(REQUIRED_OPTIONS) - options.keys())
    missing_ansi = sorted(set(range(16)) - ansi.keys())
    if missing_options or missing_ansi:
        raise ValueError(
            f"incomplete Ghostty palette at {path}: "
            f"options={missing_options}, ansi={missing_ansi}"
        )
    return options, ansi
